TransactionRecordApp/Entities/Transaction.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace TransactionRecordApp.Entities
{
    /// <summary>
    /// This class represents the columns in the Transaction table in the DB
    /// </summary>
    public class Transaction
    {
        /// <summary>
        /// this corresponds with the table PK and will work as an auto number
        /// since it's an int
        /// </summary>
        public int TransactionId { get; set; }


        [Required(ErrorMessage = "Please enter a Ticker Symbol")]
        public string? TickerSymbol { get; set; }


        [Required(ErrorMessage = "Please enter the Company Name")]
        public string? CompanyName { get; set; }


        [Required(ErrorMessage = "Please enter the quantity of shares")]
        [Range(0, int.MaxValue, ErrorMessage = "Please enter a whole number greater than zero")]
        public int? Quantity { get; set; }

        [Required(ErrorMessage = "Please enter the a share price that is greater than zero")]
        public double? SharePrice { get; set; }

		public double? GrossValue => Quantity * SharePrice;
	}
}

TransactionRecordApp/Entities/TransactionDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.EntityFrameworkCore;

namespace TransactionRecordApp.Entities
{
    /// <summary>
    /// This class will inherit from the Entity Framework (EF) class
    /// called DbContext and is used by the code to interact with the DB
    /// </summary>
    public class TransactionDbContext : DbContext
    {

		/// <summary>
		/// Define a constructor that simply passes the options argument
		/// up to the base class constuctor
		/// </summary>
		/// <param name="options"></param>
		public TransactionDbContext(DbContextOptions options)
            : base(options) { }

		public DbSet<Transaction> Transaction {  get; set; }

		// Override OnModelCreating to feed the model data
		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			modelBuilder.Entity<Transaction>().HasData(
			   new Transaction()
			   {
				   TransactionId = 1,
				   TickerSymbol = "AAPL",
				   CompanyName = "Apple",
				   Quantity = 2,
				   SharePrice = 194.62
			   },
			   new Transaction()
			   {
				   TransactionId = 2,
				   TickerSymbol = "F",
				   CompanyName = "Ford Motors Company",
				   Quantity = 4,
				   SharePrice = 11.34
			   },
			   new Transaction()
			   {
				   TransactionId = 3,
				   TickerSymbol = "GOOG",
				   CompanyName = "Alphabet Inc.",
				   Quantity = 100,
				   SharePrice = 146.51
			   },
			   new Transaction()
			   {
				   TransactionId = 4,
				   TickerSymbol = "MSFT",
				   CompanyName = "Microsoft Corporation",
				   Quantity = 100,
				   SharePrice = 397.21
			   }
		   );
		}
	}
}

TransactionRecordApp/Models/ErrorViewModel.cs
using System;

namespace TransactionRecordApp.Entities
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TransactionRecordApp/Controllers/HomeController.cs
using TransactionRecordApp.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace TransactionRecordApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TransactionRecordApp/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using TransactionRecordApp.Entities;

namespace TransactionRecordApp.Controllers
{
    /// <summary>
    /// Controls the Add, Edit and Delete functions
    /// </summary>


    public class TransactionController : Controller
    {
        // Private transaction DB context field
        private TransactionDbContext _transactionDbContext;
        
        // Constructor to set the Db context
        public TransactionController (TransactionDbContext transactionDbContext)
        {
            _transactionDbContext = transactionDbContext;
        }
        
        // Action to get a view with the all transactions in the model
        public IActionResult List()
        {
            // Get list of transactions,
            // Ordered alphabetically by company name 
            List<Transaction> transactions = _transactionDbContext.Transaction.OrderBy(t => t.CompanyName).ToList();

            return View("List", transactions);
        }
    }
}

TransactionRecordApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <p>This is the solution of Sebastian Ibanez (student #: 8760081)</p>
    <p>Here is the <a asp-controller="Transaction" asp-action="List">transactions</a> page</p>
</div>

TransactionRecordApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TransactionRecordApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TransactionRecordApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TransactionRecordApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <h1 class="display-4">@ViewData["Title"]</h1>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TransactionRecordApp
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TransactionRecordApp/Views/Transaction/List.cshtml
<!--Here we set the model type-->
@model List<Transaction>

<!--Here we set the ViewBag Title-->
@{
	ViewData["Title"] = "All transactions";
}
<table class="table table-bordered table-striped">
	<!--Here we set the table head column names-->
	<thead>
		<tr>
			<th>Ticker Symbol</th>
			<th>Company Name</th>
			<th>Quantity</th>
			<th>Share Price</th>
			<th>Gross Value</th>
		</tr>
	</thead>
	
	<!--Here we loop through the transactions in the model and add their info to the table-->
	<tbody>
		@foreach (Transaction t in Model)
		{
			<tr>
				<td>@t.TickerSymbol</td>
				<td>@t.CompanyName</td>
				<td>@t.Quantity</td>
				<td>@t.SharePrice</td>
				<td>@t.GrossValue</td>
			</tr>
		}
	</tbody>
</table>